### ISSUE TITLE
3:3 (Backends:Zeppelin ) Build Test - maven-surefire-plugin

### ISSUE THREAD

**Issue by cris83** [NFLabs/zeppelin-ci#52]
```
Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41 sec <<< FAILURE! - in org.apache.zeppelin.rest.ZeppelinRestApiTest
testNoteJobs(org.apache.zeppelin.rest.ZeppelinRestApiTest)  Time elapsed: 1.127 sec  <<< FAILURE!
java.lang.AssertionError: test notebook stop:
Expected: HTTP response <200> from /api/notebook/job/2BB443KV6
     but: got <500> Server Error
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.apache.zeppelin.rest.ZeppelinRestApiTest.testNoteJobs(ZeppelinRestApiTest.java:419)

Running org.apache.zeppelin.server.CorsFilterTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.zeppelin.server.CorsFilterTest
13:26:29,853  INFO org.apache.zeppelin.server.ZeppelinServer:123 - Shutting down Zeppelin Server ... 
13:26:29,854  INFO org.apache.zeppelin.server.ZeppelinServer:123 - Shutting down Zeppelin Server ... 
13:26:29,855  INFO org.apache.zeppelin.server.ZeppelinServer:123 - Shutting down Zeppelin Server ... 
13:26:29,855  INFO org.apache.zeppelin.server.ZeppelinServer:123 - Shutting down Zeppelin Server ... 
13:26:30,314  INFO org.apache.zeppelin.notebook.repo.NotebookRepoSync:348 - Closing all notebook storages
13:26:30,315  INFO org.apache.zeppelin.server.ZeppelinServer:131 - Bye
13:26:30,317  INFO org.apache.zeppelin.notebook.repo.NotebookRepoSync:348 - Closing all notebook storages
13:26:30,317  INFO org.apache.zeppelin.notebook.repo.NotebookRepoSync:348 - Closing all notebook storages
13:26:30,318  INFO org.apache.zeppelin.server.ZeppelinServer:131 - Bye
13:26:30,317  INFO org.apache.zeppelin.server.ZeppelinServer:131 - Bye
13:26:30,322  INFO org.apache.zeppelin.notebook.repo.NotebookRepoSync:348 - Closing all notebook storages
13:26:30,322  INFO org.apache.zeppelin.server.ZeppelinServer:131 - Bye

Results :

Failed tests: 
  ZeppelinRestApiTest.testNoteJobs:419 test notebook stop:
Expected: HTTP response <200> from /api/notebook/job/2BB443KV6
     but: got <500> Server Error

Tests run: 48, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [  7.484 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [01:24 min]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 14.945 s]
[INFO] Zeppelin: Spark dependencies ....................... SUCCESS [ 49.735 s]
[INFO] Zeppelin: Spark .................................... SUCCESS [01:13 min]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  1.428 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  0.588 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  0.522 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [  4.381 s]
[INFO] Zeppelin: Apache Phoenix Interpreter ............... SUCCESS [  6.294 s]
[INFO] Zeppelin: PostgreSQL interpreter ................... SUCCESS [  1.972 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  1.748 s]
[INFO] Zeppelin: Flink .................................... SUCCESS [ 22.450 s]
[INFO] Zeppelin: Apache Ignite interpreter ................ SUCCESS [ 23.094 s]
[INFO] Zeppelin: Kylin interpreter ........................ SUCCESS [  1.119 s]
[INFO] Zeppelin: Lens interpreter ......................... SUCCESS [  5.924 s]
[INFO] Zeppelin: Cassandra ................................ SUCCESS [ 58.473 s]
[INFO] Zeppelin: Elasticsearch interpreter ................ SUCCESS [ 18.825 s]
[INFO] Zeppelin: web Application .......................... SUCCESS [01:43 min]
[INFO] Zeppelin: Server ................................... FAILURE [01:27 min]
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:29 min
[INFO] Finished at: 2016-01-18T13:26:30+00:00
[INFO] Final Memory: 125M/4313M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project zeppelin-server: There are test failures.
```

**Comment by cris83** [comment]
* 3:4 구조 test ( parallel 2set )
```
Results :

Failed tests: 
  RemoteSchedulerTest.testAbortOnPending:264 null

Tests run: 36, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [ 17.588 s]
[INFO] Zeppelin: Interpreter .............................. FAILURE [02:28 min]
[INFO] Zeppelin: Zengine .................................. SKIPPED
[INFO] Zeppelin: Spark dependencies ....................... SKIPPED
[INFO] Zeppelin: Spark .................................... SKIPPED
[INFO] Zeppelin: Markdown interpreter ..................... SKIPPED
[INFO] Zeppelin: Angular interpreter ...................... SKIPPED
[INFO] Zeppelin: Shell interpreter ........................ SKIPPED
[INFO] Zeppelin: Hive interpreter ......................... SKIPPED
[INFO] Zeppelin: Apache Phoenix Interpreter ............... SKIPPED
[INFO] Zeppelin: PostgreSQL interpreter ................... SKIPPED
[INFO] Zeppelin: Tajo interpreter ......................... SKIPPED
[INFO] Zeppelin: Flink .................................... SKIPPED
[INFO] Zeppelin: Apache Ignite interpreter ................ SKIPPED
[INFO] Zeppelin: Kylin interpreter ........................ SKIPPED
[INFO] Zeppelin: Lens interpreter ......................... SKIPPED
[INFO] Zeppelin: Cassandra ................................ SKIPPED
[INFO] Zeppelin: Elasticsearch interpreter ................ SKIPPED
[INFO] Zeppelin: web Application .......................... SKIPPED
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] Zeppelin: Scalding interpreter ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2016-01-19T09:52:42+00:00
[INFO] Final Memory: 44M/1932M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project zeppelin-interpreter: There are test failures.
```
